# Build stage
FROM node:20-alpine as build

WORKDIR /app

COPY package.json yarn.lock ./
# Use yarn for reproducible builds in Docker
RUN yarn install --frozen-lockfile
COPY . .
RUN yarn build

# Production stage
FROM nginx:alpine

# Copy built app and nginx conf (without SSL, external nginx handles SSL)
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf.prod /etc/nginx/conf.d/default.conf
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

