/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SandboxRouteImport } from './routes/sandbox'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VaultsIndexRouteImport } from './routes/vaults/index'
import { Route as VaultsMyRouteImport } from './routes/vaults/my'
import { Route as VaultsIdRouteImport } from './routes/vaults/$id'

const SandboxRoute = SandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultsIndexRoute = VaultsIndexRouteImport.update({
  id: '/vaults/',
  path: '/vaults/',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultsMyRoute = VaultsMyRouteImport.update({
  id: '/vaults/my',
  path: '/vaults/my',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultsIdRoute = VaultsIdRouteImport.update({
  id: '/vaults/$id',
  path: '/vaults/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/profile': typeof ProfileRoute
  '/sandbox': typeof SandboxRoute
  '/vaults/$id': typeof VaultsIdRoute
  '/vaults/my': typeof VaultsMyRoute
  '/vaults': typeof VaultsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/profile': typeof ProfileRoute
  '/sandbox': typeof SandboxRoute
  '/vaults/$id': typeof VaultsIdRoute
  '/vaults/my': typeof VaultsMyRoute
  '/vaults': typeof VaultsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/profile': typeof ProfileRoute
  '/sandbox': typeof SandboxRoute
  '/vaults/$id': typeof VaultsIdRoute
  '/vaults/my': typeof VaultsMyRoute
  '/vaults/': typeof VaultsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/profile'
    | '/sandbox'
    | '/vaults/$id'
    | '/vaults/my'
    | '/vaults'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/profile'
    | '/sandbox'
    | '/vaults/$id'
    | '/vaults/my'
    | '/vaults'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/profile'
    | '/sandbox'
    | '/vaults/$id'
    | '/vaults/my'
    | '/vaults/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  ProfileRoute: typeof ProfileRoute
  SandboxRoute: typeof SandboxRoute
  VaultsIdRoute: typeof VaultsIdRoute
  VaultsMyRoute: typeof VaultsMyRoute
  VaultsIndexRoute: typeof VaultsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sandbox': {
      id: '/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof SandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vaults/': {
      id: '/vaults/'
      path: '/vaults'
      fullPath: '/vaults'
      preLoaderRoute: typeof VaultsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vaults/my': {
      id: '/vaults/my'
      path: '/vaults/my'
      fullPath: '/vaults/my'
      preLoaderRoute: typeof VaultsMyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vaults/$id': {
      id: '/vaults/$id'
      path: '/vaults/$id'
      fullPath: '/vaults/$id'
      preLoaderRoute: typeof VaultsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  ProfileRoute: ProfileRoute,
  SandboxRoute: SandboxRoute,
  VaultsIdRoute: VaultsIdRoute,
  VaultsMyRoute: VaultsMyRoute,
  VaultsIndexRoute: VaultsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
