/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TokensRouteImport } from './routes/tokens'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as SwapRouteImport } from './routes/swap'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as CreateRouteImport } from './routes/create'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VaultsIndexRouteImport } from './routes/vaults/index'
import { Route as RewardsIndexRouteImport } from './routes/rewards/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as VaultsIdRouteImport } from './routes/vaults/$id'
import { Route as RewardsVestingRouteImport } from './routes/rewards/vesting'
import { Route as RewardsVaultsRouteImport } from './routes/rewards/vaults'
import { Route as RewardsEpochsRouteImport } from './routes/rewards/epochs'
import { Route as ProposalsIdRouteImport } from './routes/proposals/$id'
import { Route as ProfileIdRouteImport } from './routes/profile/$id'
import { Route as RewardsVaultsIndexRouteImport } from './routes/rewards/vaults/index'
import { Route as RewardsVaultsVaultIdRouteImport } from './routes/rewards/vaults/$vaultId'
import { Route as RewardsEpochsIdRouteImport } from './routes/rewards/epochs/$id'

const TokensRoute = TokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const SwapRoute = SwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultsIndexRoute = VaultsIndexRouteImport.update({
  id: '/vaults/',
  path: '/vaults/',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsIndexRoute = RewardsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RewardsRoute,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultsIdRoute = VaultsIdRouteImport.update({
  id: '/vaults/$id',
  path: '/vaults/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsVestingRoute = RewardsVestingRouteImport.update({
  id: '/vesting',
  path: '/vesting',
  getParentRoute: () => RewardsRoute,
} as any)
const RewardsVaultsRoute = RewardsVaultsRouteImport.update({
  id: '/vaults',
  path: '/vaults',
  getParentRoute: () => RewardsRoute,
} as any)
const RewardsEpochsRoute = RewardsEpochsRouteImport.update({
  id: '/epochs',
  path: '/epochs',
  getParentRoute: () => RewardsRoute,
} as any)
const ProposalsIdRoute = ProposalsIdRouteImport.update({
  id: '/proposals/$id',
  path: '/proposals/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsVaultsIndexRoute = RewardsVaultsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RewardsVaultsRoute,
} as any)
const RewardsVaultsVaultIdRoute = RewardsVaultsVaultIdRouteImport.update({
  id: '/$vaultId',
  path: '/$vaultId',
  getParentRoute: () => RewardsVaultsRoute,
} as any)
const RewardsEpochsIdRoute = RewardsEpochsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RewardsEpochsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/create': typeof CreateRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/rewards': typeof RewardsRouteWithChildren
  '/swap': typeof SwapRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/tokens': typeof TokensRoute
  '/profile/$id': typeof ProfileIdRoute
  '/proposals/$id': typeof ProposalsIdRoute
  '/rewards/epochs': typeof RewardsEpochsRouteWithChildren
  '/rewards/vaults': typeof RewardsVaultsRouteWithChildren
  '/rewards/vesting': typeof RewardsVestingRoute
  '/vaults/$id': typeof VaultsIdRoute
  '/profile': typeof ProfileIndexRoute
  '/rewards/': typeof RewardsIndexRoute
  '/vaults': typeof VaultsIndexRoute
  '/rewards/epochs/$id': typeof RewardsEpochsIdRoute
  '/rewards/vaults/$vaultId': typeof RewardsVaultsVaultIdRoute
  '/rewards/vaults/': typeof RewardsVaultsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/create': typeof CreateRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/swap': typeof SwapRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/tokens': typeof TokensRoute
  '/profile/$id': typeof ProfileIdRoute
  '/proposals/$id': typeof ProposalsIdRoute
  '/rewards/epochs': typeof RewardsEpochsRouteWithChildren
  '/rewards/vesting': typeof RewardsVestingRoute
  '/vaults/$id': typeof VaultsIdRoute
  '/profile': typeof ProfileIndexRoute
  '/rewards': typeof RewardsIndexRoute
  '/vaults': typeof VaultsIndexRoute
  '/rewards/epochs/$id': typeof RewardsEpochsIdRoute
  '/rewards/vaults/$vaultId': typeof RewardsVaultsVaultIdRoute
  '/rewards/vaults': typeof RewardsVaultsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/create': typeof CreateRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/rewards': typeof RewardsRouteWithChildren
  '/swap': typeof SwapRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/tokens': typeof TokensRoute
  '/profile/$id': typeof ProfileIdRoute
  '/proposals/$id': typeof ProposalsIdRoute
  '/rewards/epochs': typeof RewardsEpochsRouteWithChildren
  '/rewards/vaults': typeof RewardsVaultsRouteWithChildren
  '/rewards/vesting': typeof RewardsVestingRoute
  '/vaults/$id': typeof VaultsIdRoute
  '/profile/': typeof ProfileIndexRoute
  '/rewards/': typeof RewardsIndexRoute
  '/vaults/': typeof VaultsIndexRoute
  '/rewards/epochs/$id': typeof RewardsEpochsIdRoute
  '/rewards/vaults/$vaultId': typeof RewardsVaultsVaultIdRoute
  '/rewards/vaults/': typeof RewardsVaultsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/create'
    | '/how-it-works'
    | '/privacy-policy'
    | '/rewards'
    | '/swap'
    | '/terms-of-service'
    | '/tokens'
    | '/profile/$id'
    | '/proposals/$id'
    | '/rewards/epochs'
    | '/rewards/vaults'
    | '/rewards/vesting'
    | '/vaults/$id'
    | '/profile'
    | '/rewards/'
    | '/vaults'
    | '/rewards/epochs/$id'
    | '/rewards/vaults/$vaultId'
    | '/rewards/vaults/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/create'
    | '/how-it-works'
    | '/privacy-policy'
    | '/swap'
    | '/terms-of-service'
    | '/tokens'
    | '/profile/$id'
    | '/proposals/$id'
    | '/rewards/epochs'
    | '/rewards/vesting'
    | '/vaults/$id'
    | '/profile'
    | '/rewards'
    | '/vaults'
    | '/rewards/epochs/$id'
    | '/rewards/vaults/$vaultId'
    | '/rewards/vaults'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/create'
    | '/how-it-works'
    | '/privacy-policy'
    | '/rewards'
    | '/swap'
    | '/terms-of-service'
    | '/tokens'
    | '/profile/$id'
    | '/proposals/$id'
    | '/rewards/epochs'
    | '/rewards/vaults'
    | '/rewards/vesting'
    | '/vaults/$id'
    | '/profile/'
    | '/rewards/'
    | '/vaults/'
    | '/rewards/epochs/$id'
    | '/rewards/vaults/$vaultId'
    | '/rewards/vaults/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  CreateRoute: typeof CreateRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RewardsRoute: typeof RewardsRouteWithChildren
  SwapRoute: typeof SwapRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  TokensRoute: typeof TokensRoute
  ProfileIdRoute: typeof ProfileIdRoute
  ProposalsIdRoute: typeof ProposalsIdRoute
  VaultsIdRoute: typeof VaultsIdRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  VaultsIndexRoute: typeof VaultsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tokens': {
      id: '/tokens'
      path: '/tokens'
      fullPath: '/tokens'
      preLoaderRoute: typeof TokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swap': {
      id: '/swap'
      path: '/swap'
      fullPath: '/swap'
      preLoaderRoute: typeof SwapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vaults/': {
      id: '/vaults/'
      path: '/vaults'
      fullPath: '/vaults'
      preLoaderRoute: typeof VaultsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards/': {
      id: '/rewards/'
      path: '/'
      fullPath: '/rewards/'
      preLoaderRoute: typeof RewardsIndexRouteImport
      parentRoute: typeof RewardsRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vaults/$id': {
      id: '/vaults/$id'
      path: '/vaults/$id'
      fullPath: '/vaults/$id'
      preLoaderRoute: typeof VaultsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards/vesting': {
      id: '/rewards/vesting'
      path: '/vesting'
      fullPath: '/rewards/vesting'
      preLoaderRoute: typeof RewardsVestingRouteImport
      parentRoute: typeof RewardsRoute
    }
    '/rewards/vaults': {
      id: '/rewards/vaults'
      path: '/vaults'
      fullPath: '/rewards/vaults'
      preLoaderRoute: typeof RewardsVaultsRouteImport
      parentRoute: typeof RewardsRoute
    }
    '/rewards/epochs': {
      id: '/rewards/epochs'
      path: '/epochs'
      fullPath: '/rewards/epochs'
      preLoaderRoute: typeof RewardsEpochsRouteImport
      parentRoute: typeof RewardsRoute
    }
    '/proposals/$id': {
      id: '/proposals/$id'
      path: '/proposals/$id'
      fullPath: '/proposals/$id'
      preLoaderRoute: typeof ProposalsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards/vaults/': {
      id: '/rewards/vaults/'
      path: '/'
      fullPath: '/rewards/vaults/'
      preLoaderRoute: typeof RewardsVaultsIndexRouteImport
      parentRoute: typeof RewardsVaultsRoute
    }
    '/rewards/vaults/$vaultId': {
      id: '/rewards/vaults/$vaultId'
      path: '/$vaultId'
      fullPath: '/rewards/vaults/$vaultId'
      preLoaderRoute: typeof RewardsVaultsVaultIdRouteImport
      parentRoute: typeof RewardsVaultsRoute
    }
    '/rewards/epochs/$id': {
      id: '/rewards/epochs/$id'
      path: '/$id'
      fullPath: '/rewards/epochs/$id'
      preLoaderRoute: typeof RewardsEpochsIdRouteImport
      parentRoute: typeof RewardsEpochsRoute
    }
  }
}

interface RewardsEpochsRouteChildren {
  RewardsEpochsIdRoute: typeof RewardsEpochsIdRoute
}

const RewardsEpochsRouteChildren: RewardsEpochsRouteChildren = {
  RewardsEpochsIdRoute: RewardsEpochsIdRoute,
}

const RewardsEpochsRouteWithChildren = RewardsEpochsRoute._addFileChildren(
  RewardsEpochsRouteChildren,
)

interface RewardsVaultsRouteChildren {
  RewardsVaultsVaultIdRoute: typeof RewardsVaultsVaultIdRoute
  RewardsVaultsIndexRoute: typeof RewardsVaultsIndexRoute
}

const RewardsVaultsRouteChildren: RewardsVaultsRouteChildren = {
  RewardsVaultsVaultIdRoute: RewardsVaultsVaultIdRoute,
  RewardsVaultsIndexRoute: RewardsVaultsIndexRoute,
}

const RewardsVaultsRouteWithChildren = RewardsVaultsRoute._addFileChildren(
  RewardsVaultsRouteChildren,
)

interface RewardsRouteChildren {
  RewardsEpochsRoute: typeof RewardsEpochsRouteWithChildren
  RewardsVaultsRoute: typeof RewardsVaultsRouteWithChildren
  RewardsVestingRoute: typeof RewardsVestingRoute
  RewardsIndexRoute: typeof RewardsIndexRoute
}

const RewardsRouteChildren: RewardsRouteChildren = {
  RewardsEpochsRoute: RewardsEpochsRouteWithChildren,
  RewardsVaultsRoute: RewardsVaultsRouteWithChildren,
  RewardsVestingRoute: RewardsVestingRoute,
  RewardsIndexRoute: RewardsIndexRoute,
}

const RewardsRouteWithChildren =
  RewardsRoute._addFileChildren(RewardsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  CreateRoute: CreateRoute,
  HowItWorksRoute: HowItWorksRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RewardsRoute: RewardsRouteWithChildren,
  SwapRoute: SwapRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  TokensRoute: TokensRoute,
  ProfileIdRoute: ProfileIdRoute,
  ProposalsIdRoute: ProposalsIdRoute,
  VaultsIdRoute: VaultsIdRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  VaultsIndexRoute: VaultsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
